### ISSUE TITLE
packages/devel/ccache/package.mk needs updating

### ISSUE THREAD

**Issue by Andy-ABTec** [OpenELEC/OpenELEC.tv#5006]
Apologies - I'm new to GitHub and am still finding my way around...

It would appear that ccache.org has changed to using https rather than http so lines 24 and 25 of package.mk need tweaking...

Again, apologies if I've got this wrong, but manually editing the file and running "make image" works for me...

Andy B.

**Comment by sghazagh** [comment]
Thanks mate, you saved my day!

**Comment by sghazagh** [comment]
Fail on "libcec" compile!

Do you have the issue with 'libcec' preventing completion of image creation?

**Comment by Andy-ABTec** [comment]
Wont know for a while - my linux vm is REALLY SLOW, I'll get back to you...

**Comment by sghazagh** [comment]
Thanks,
I don't know why 7.0.1 has this much issues!
Last time I did the compile on OE7.0 and it has compiled with no issue!!!

**Comment by Andy-ABTec** [comment]
Still don't know having problems with zlib viz:
```
In file included from /root/OpenELEC.tv/build.OpenELEC-imx6.arm-8.0-devel/libpng-1.6.28/scripts/intprefix.c:22:0:
/root/OpenELEC.tv/build.OpenELEC-imx6.arm-8.0-devel/libpng-1.6.28/scripts/../pngpriv.h:849:4: error: #error ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the notes in pngpriv.h"
 #  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
    ^
CMake Error at scripts/genout.cmake:78 (message):
  Failed to generate
  /root/OpenELEC.tv/build.OpenELEC-imx6.arm-8.0-devel/libpng-1.6.28/.i586-linux-gnu/scripts/intprefix.out.tf1
```

**Comment by sghazagh** [comment]
Have you changed the zlib version?
Check my post here: https://github.com/OpenELEC/OpenELEC.tv/issues/5003
I could fix the compile issue by using version 1.2.11 instead of 1.2.10.

**Comment by Andy-ABTec** [comment]
Been there, done that, still got the problem...

Currently tracking down ZLIB_VERNUM and PNG_ZLIB_VERNUM to try and work out what's going on.

**Comment by Andy-ABTec** [comment]
Now I'm really confused...

```
root@test-01:~/OpenELEC.tv# grep -r "define ZLIB_VERNUM" *
build.OpenELEC-imx6.arm-8.0-devel/toolchain/armv7a-openelec-linux-gnueabi/sysroot/usr/include/zlib.h:#define ZLIB_VERNUM 0x12b0
build.OpenELEC-imx6.arm-8.0-devel/toolchain/include/zlib.h:#define ZLIB_VERNUM 0x12b0
build.OpenELEC-imx6.arm-8.0-devel/ccache-3.3.3/zlib/zlib.h:#define ZLIB_VERNUM 0x1280
build.OpenELEC-imx6.arm-8.0-devel/Python-2.7.13/Modules/zlib/zlib.h:#define ZLIB_VERNUM 0x1280
build.OpenELEC-imx6.arm-8.0-devel/zlib-1.2.11/zlib.h:#define ZLIB_VERNUM 0x12b0
build.OpenELEC-imx6.arm-8.0-devel/zlib-1.2.11/.install_dev/usr/include/zlib.h:#define ZLIB_VERNUM 0x12b0
build.OpenELEC-imx6.arm-8.0-devel/zlib-1.2.11/.i586-linux-gnu/zlib.h:#define ZLIB_VERNUM 0x12b0
build.OpenELEC-imx6.arm-8.0-devel/zlib-1.2.11/.armv7a-openelec-linux-gnueabi/zlib.h:#define ZLIB_VERNUM 0x12b0
build.OpenELEC-imx6.arm-8.0-devel/gcc-6.3.0/zlib/zlib.h:#define ZLIB_VERNUM 0x1280
build.OpenELEC-imx6.arm-8.0-devel/binutils-2.27/zlib/zlib.h:#define ZLIB_VERNUM 0x1280
build.OpenELEC-imx6.arm-8.0-devel/cmake-3.7.2/.i586-linux-gnu/Utilities/cmzlib/zlib.h:#define ZLIB_VERNUM 0x1230
build.OpenELEC-imx6.arm-8.0-devel/cmake-3.7.2/Utilities/cmzlib/zlib.h:#define ZLIB_VERNUM 0x1230
build.OpenELEC-imx6.arm-8.0-devel/kodi-1dd8613/lib/libUPnP/Neptune/ThirdParty/zlib-1.2.3/zlib.h:#define ZLIB_VERNUM 0x1230
build.OpenELEC-imx6.arm-8.0-devel/kodi-1dd8613/lib/libUPnP/Neptune/ThirdParty/zlib-1.2.8/zlib.h:#define ZLIB_VERNUM 0x1280
build.OpenELEC-imx6.arm-8.0-devel/u-boot-10acd12/include/u-boot/zlib.h:#define ZLIB_VERNUM 0x1230

root@test-01:~/OpenELEC.tv# grep -r "define PNG_ZLIB_VERNUM" *
build.OpenELEC-imx6.arm-8.0-devel/toolchain/include/pnglibconf.h:#define PNG_ZLIB_VERNUM 0x1280
build.OpenELEC-imx6.arm-8.0-devel/toolchain/include/libpng16/pnglibconf.h:#define PNG_ZLIB_VERNUM 0x1280
build.OpenELEC-imx6.arm-8.0-devel/libpng-1.6.28/scripts/pnglibconf.h.prebuilt:#define PNG_ZLIB_VERNUM 0 /* unknown */
build.OpenELEC-imx6.arm-8.0-devel/libpng-1.6.28/.i586-linux-gnu/pnglibconf.out:#define PNG_ZLIB_VERNUM 0x12b0
build.OpenELEC-imx6.arm-8.0-devel/libpng-1.6.28/.i586-linux-gnu/pnglibconf.h:#define PNG_ZLIB_VERNUM 0x12b0
build.OpenELEC-imx6.arm-8.0-devel/libpng-1.6.28/.i586-linux-gnu/pnglibconf.c: PNG_DFN "#define PNG_ZLIB_VERNUM @" PNG_ZLIB_VERNUM "@"
build.OpenELEC-imx6.arm-8.0-devel/libpng-1.6.28/.i586-linux-gnu/pnglibconf.c: PNG_DFN "#define PNG_ZLIB_VERNUM @" PNG_set_ZLIB_VERNUM "@"
build.OpenELEC-imx6.arm-8.0-devel/libpng-1.6.28/.i586-linux-gnu/pnglibconf.c:#  define PNG_ZLIB_VERNUM 1
build.OpenELEC-imx6.arm-8.0-devel/libpng-1.6.28/.i586-linux-gnu/pnglibconf.c: PNG_DFN "#define PNG_ZLIB_VERNUM @" ZLIB_VERNUM "@"
build.OpenELEC-imx6.arm-8.0-devel/libpng-1.6.28/.i586-linux-gnu/pnglibconf.c:#  define PNG_ZLIB_VERNUM 1
```

**Comment by lrusak** [comment]
don't build as root is a good place to start

**Comment by sghazagh** [comment]
Gave up on OpenELEC. Switched to LiberELEC and the compile ran smoothly.
Guys at LiberELEC are well organized and are much tidier that OpenELEC fellows.

Have compiled LibreELEC 7.0.3 and all is good now!

**Comment by sraue** [comment]
you always could send a PR for the zlib bump and try to be a bit more patient.

**Comment by Raybuntu** [comment]
Have a look here
https://github.com/LibreELEC/LibreELEC.tv/commits/master/packages/devel/ccache/package.mk
git cherry-pick is your friend. We don't need to reinvent the wheel all over again.

**Comment by sghazagh** [comment]
@sraue 
Stephan, I didn't mean to dis value your all great works.
But you guys should take more attention when you release an update. Thousand of people realiying on your OS so we have to trust that the releases are all OK to upgrade our devices.

This is not a first time that a release do not compile properly.
Please take care of it...

**Comment by sghazagh** [comment]
Ok all,
Just to confirm that I could compile OpenELEC 7.0.1 for RPi2 successfully by making these changes:
- ccach package source should be changed to https as explained in this post
- samba also has a same issue, changed it to https and it downloaded and compiled just fine!
- zlib needs to be changed to 1.2.11 instead of 1.2.10 (Also explained above)

After that, the compile done successfully and I could get my image (.img) and update (.tar) files.

**Comment by sraue** [comment]
fixed in https://github.com/OpenELEC/OpenELEC.tv/commit/4cc0ad30b013192e2696660cdba077ea24c30c59 https://github.com/OpenELEC/OpenELEC.tv/commit/3b833973ac7243cb3b6b2166689d4832a4f892f2 https://github.com/OpenELEC/OpenELEC.tv/commit/30a5dcbaced4e52aede161e3b15df984387442f6 and https://github.com/OpenELEC/OpenELEC.tv/commit/332e91ecb5a21d7e5cd17aa36d1dbe1884b2742e

thanks much @all 

@sghazagh regarding "This is not a first time that a release do not compile properly." this happens because the upstream projects in this case changed the download urls AFTER we released the last release and/or provided a updated package with removed the version before (which happens rarly). This we cant avoid, and its not much a problem because self builders should handle this (and report/provide the needed changes). for normal users this dont matter
